language: python
python:
  - "3.8"

branches:
  only:
  - master

services:
  - docker

before_install:
  - pip install flake8
  - ./scripts/setup

script:
  - ./scripts/test

deploy:
  provider: script
  script: bash scripts/deploy
  on:
    branch: master
