# Generated by Django 2.2.8 on 2020-01-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_optioncorrelation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
