# Generated by Django 2.2.8 on 2020-01-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20200111_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioncorrelation',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
